server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: query-service
          uri: lb://query-service
          predicates:
              - Path=/query/**

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: social-cooking-client
            client-secret: fSIyShvcGneQyiVIst42xjSzzFYS8cgb
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8000/auth/realms/social-cooking
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/auth/realms/social-cooking

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG